apiVersion: nifi.konpyutaika.com/v1
kind: NifiCluster
metadata:
  creationTimestamp: '2025-03-20T08:36:08Z'
  generation: 7
  managedFields:
    - apiVersion: nifi.konpyutaika.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:service':
            .: {}
            'f:headlessEnabled': {}
            'f:labels':
              .: {}
              'f:cluster-name': {}
          'f:clusterManager': {}
          'f:nifiClusterTaskSpec':
            .: {}
            'f:retryDurationMinutes': {}
          'f:zkPath': {}
          'f:nodeConfigGroups':
            .: {}
            'f:default_group':
              .: {}
              'f:fsGroup': {}
              'f:imagePullPolicy': {}
              'f:isNode': {}
              'f:resourcesRequirements':
                .: {}
                'f:limits':
                  .: {}
                  'f:cpu': {}
                  'f:memory': {}
                'f:requests':
                  .: {}
                  'f:cpu': {}
                  'f:memory': {}
              'f:runAsUser': {}
              'f:serviceAccountName': {}
              'f:storageConfigs': {}
          'f:oneNifiNodePerNode': {}
          'f:listenersConfig':
            .: {}
            'f:internalListeners': {}
          .: {}
          'f:zkAddress': {}
          'f:pod':
            .: {}
            'f:labels':
              .: {}
              'f:cluster-name': {}
          'f:propagateLabels': {}
          'f:clusterImage': {}
          'f:readOnlyConfig':
            .: {}
            'f:nifiProperties':
              .: {}
              'f:overrideConfigs': {}
          'f:externalServices': {}
          'f:nodes': {}
          'f:initContainerImage': {}
      manager: Mozilla
      operation: Update
      time: '2025-03-20T09:38:40Z'
    - apiVersion: nifi.konpyutaika.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:nodesState':
            .: {}
            'f:1':
              .: {}
              'f:configurationState': {}
              'f:creationTime': {}
              'f:gracefulActionState':
                .: {}
                'f:TaskStarted': {}
                'f:actionState': {}
                'f:actionStep': {}
                'f:errorMessage': {}
              'f:initClusterNode': {}
              'f:lastUpdatedTime': {}
              'f:podIsReady': {}
            'f:2':
              .: {}
              'f:configurationState': {}
              'f:creationTime': {}
              'f:gracefulActionState':
                .: {}
                'f:actionState': {}
                'f:errorMessage': {}
              'f:initClusterNode': {}
              'f:lastUpdatedTime': {}
              'f:podIsReady': {}
          'f:prometheusReportingTask':
            .: {}
            'f:id': {}
            'f:version': {}
          'f:rollingUpgradeStatus':
            .: {}
            'f:errorCount': {}
            'f:lastSuccess': {}
          'f:state': {}
      manager: manager
      operation: Update
      subresource: status
      time: '2025-03-20T10:07:08Z'
  name: nifidemo
  namespace: test-java-playground
  resourceVersion: '3731956145'
  uid: e912d6ed-9c01-4e5f-8b99-996f6fb53bd4
spec:
  listenersConfig:
    internalListeners:
      - containerPort: 8081
        name: http
        protocol: TCP
        type: http
      - containerPort: 6007
        name: cluster
        protocol: TCP
        type: cluster
      - containerPort: 10000
        name: s2s
        protocol: TCP
        type: s2s
      - containerPort: 9090
        name: prometheus
        protocol: TCP
        type: prometheus
      - containerPort: 6342
        name: load-balance
        protocol: TCP
        type: load-balance
  clusterImage: 'apache/nifi:2.3.0'
  zkAddress: 'zookeeper.test-java-playground.svc.cluster.local:2181'
  readOnlyConfig:
    nifiProperties:
      overrideConfigs: |
        nifi.sensitive.props.key=thisIsABadSensitiveKeyPassword
  pod:
    labels:
      cluster-name: nifidemo
  propagateLabels: true
  externalServices:
    - metadata:
        labels:
          cluster-name: driver-nifidemo
      name: driver-ip
      spec:
        portConfigs:
          - internalListenerName: http
            port: 8081
            protocol: TCP
        type: LoadBalancer
  initContainerImage: 'bash:5.2.2'
  nodes:
    - id: 1
      nodeConfigGroup: default_group
    - id: 2
      nodeConfigGroup: default_group
  clusterManager: zookeeper
  service:
    headlessEnabled: true
    labels:
      cluster-name: nifidemo
  zkPath: /nifidemo
  nodeConfigGroups:
    default_group:
      fsGroup: 1001270000
      imagePullPolicy: IfNotPresent
      isNode: true
      resourcesRequirements:
        limits:
          cpu: '1'
          memory: 2Gi
        requests:
          cpu: '1'
          memory: 2Gi
      runAsUser: 1001270000
      serviceAccountName: nifikop
      storageConfigs:
        - mountPath: /opt/nifi/nifi-current/logs
          name: logs
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: csi-vmware-block
          reclaimPolicy: Delete
  oneNifiNodePerNode: true
  nifiClusterTaskSpec:
    retryDurationMinutes: 10
status:
  nodesState:
    '1':
      configurationState: ConfigInSync
      creationTime: '2025-03-20T08:44:30Z'
      gracefulActionState:
        TaskStarted: 'Thu, 20 Mar 2025 10:07:04 GMT'
        actionState: GracefulUpscaleRunning
        actionStep: CONNECTING
        errorMessage: ''
      initClusterNode: true
      lastUpdatedTime: '2025-03-20T10:07:04Z'
      podIsReady: false
    '2':
      configurationState: ConfigInSync
      creationTime: '2025-03-20T08:44:30Z'
      gracefulActionState:
        actionState: GracefulUpscaleRequired
        errorMessage: ''
      initClusterNode: true
      lastUpdatedTime: '2025-03-20T10:07:08Z'
      podIsReady: false
  prometheusReportingTask:
    id: ''
    version: 0
  rollingUpgradeStatus:
    errorCount: 0
    lastSuccess: ''
  state: ClusterRollingUpgrading
