apiVersion: nifi.konpyutaika.com/v1
kind: NifiCluster
metadata:
  creationTimestamp: '2025-03-21T13:39:56Z'
  generation: 9
  name: nifidemo
  namespace: test-java-playground
  resourceVersion: '3751107075'
  uid: bf57df6e-bdff-4328-8b8b-6a715bb8f52e
spec:
  clusterImage: 'apache/nifi:2.3.0'
  clusterManager: zookeeper
  externalServices:
    - metadata:
        labels:
          cluster-name: driver-nifidemo
      name: driver-ip
      spec:
        portConfigs:
          - internalListenerName: http
            port: 8081
            protocol: TCP
        type: LoadBalancer
  initContainerImage: 'bash:5.2.2'
  listenersConfig:
    internalListeners:
      - containerPort: 8081
        name: http
        protocol: TCP
        type: http
      - containerPort: 6007
        name: cluster
        protocol: TCP
        type: cluster
      - containerPort: 10000
        name: s2s
        protocol: TCP
        type: s2s
      - containerPort: 9090
        name: prometheus
        protocol: TCP
        type: prometheus
      - containerPort: 6342
        name: load-balance
        protocol: TCP
        type: load-balance
  nifiClusterTaskSpec:
    retryDurationMinutes: 10
  nodeConfigGroups:
    default_group:
      fsGroup: 1001270000
      imagePullPolicy: IfNotPresent
      isNode: true
      resourcesRequirements:
        limits:
          cpu: '1'
          memory: 2Gi
        requests:
          cpu: '1'
          memory: 2Gi
      runAsUser: 1001270000
      serviceAccountName: nifikop
      storageConfigs:
        - mountPath: /opt/nifi/nifi-current/logs
          name: logs
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: csi-vmware-block
          reclaimPolicy: Delete
        - metadata:
            annotations:
              my-annotation: nifidemo
            labels:
              my-label: nifidemo
          mountPath: /opt/nifi/data
          name: data
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            storageClassName: csi-vmware-block
          reclaimPolicy: Delete
        - metadata:
            annotations:
              my-annotation: my-value
            labels:
              my-label: my-value
          mountPath: /opt/nifi/extensions
          name: extensions-repository
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            storageClassName: csi-vmware-block
          reclaimPolicy: Delete
        - metadata:
            annotations:
              my-annotation: nifidemo
            labels:
              my-label: nifidemo
          mountPath: /opt/nifi/flowfile_repository
          name: flowfile-repository
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: csi-vmware-block
          reclaimPolicy: Delete
        - metadata:
            annotations:
              my-annotation: nifidemo
            labels:
              my-label: nifidemo
          mountPath: /opt/nifi/nifi-current/conf
          name: conf
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            storageClassName: csi-vmware-block
          reclaimPolicy: Delete
        - metadata:
            annotations:
              my-annotation: nifidemo
            labels:
              my-label: nifidemo
          mountPath: /opt/nifi/nifi-current/bin
          name: bin
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            storageClassName: csi-vmware-block
          reclaimPolicy: Delete
        - metadata:
            annotations:
              my-annotation: nifidemo
            labels:
              my-label: nifidemo
          mountPath: /opt/nifi/content_repository
          name: content-repository
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            storageClassName: csi-vmware-block
          reclaimPolicy: Delete
        - metadata:
            annotations:
              my-annotation: nifidemo
            labels:
              my-label: nifidemo
          mountPath: /opt/nifi/provenance_repository
          name: provenance-repository
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
          reclaimPolicy: Delete
  nodes:
    - id: 1
      nodeConfigGroup: default_group
    - id: 2
      nodeConfigGroup: default_group
  oneNifiNodePerNode: true
  pod:
    labels:
      cluster-name: nifidemo
  propagateLabels: true
  readOnlyConfig:
    nifiProperties:
      overrideConfigs: |
        nifi.sensitive.props.key=thisIsABadSensitiveKeyPassword
  service:
    headlessEnabled: true
    labels:
      cluster-name: nifidemo
  zkAddress: 'zookeeper.test-java-playground.svc.cluster.local:2181'
  zkPath: /nifidemo
status:
  nodesState:
    '1':
      configurationState: ConfigInSync
      creationTime: '2025-03-21T13:39:56Z'
      gracefulActionState:
        actionState: GracefulUpscaleRequired
        errorMessage: ''
      initClusterNode: true
      lastUpdatedTime: '2025-03-27T09:56:46Z'
      podIsReady: false
    '2':
      configurationState: ConfigInSync
      creationTime: '2025-03-21T13:39:56Z'
      gracefulActionState:
        TaskStarted: 'Thu, 27 Mar 2025 09:38:02 GMT'
        actionState: GracefulUpscaleRunning
        actionStep: CONNECTING
        errorMessage: ''
      initClusterNode: true
      lastUpdatedTime: '2025-03-27T09:38:02Z'
      podIsReady: false
  prometheusReportingTask:
    id: ''
    version: 0
  rollingUpgradeStatus:
    errorCount: 0
    lastSuccess: ''
  state: ClusterRollingUpgrading
